#  mysql.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-pw
                  key: root_password
            #  value: mypass  # db 관리자 암호
            - name: MYSQL_DATABASE # database 이름
              valueFrom: 
                configMapKeyRef:
                  name: config-db
                  key: MYSQL_DATABASE
            - name: MYSQL_USER # database에 권한이있는 user
              valueFrom: 
                configMapKeyRef:
                  name: config-db
                  key: MYSQL_USER
            - name: MYSQL_ROOT_HOST # 접근 호스트
              valueFrom: 
                configMapKeyRef:
                  name: config-db
                  key: MYSQL_ROOT_HOST
            - name: MYSQL_PASSWORD # DB 계정(myuser)의 암호
              valueFrom:
                secretKeyRef:
                  name: db-pw
                  key: user_password

          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-volumeclaim


